# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David's Blog
email: dlapsley@cisco.com
description: > # this means to ignore newlines until "baseurl:"
    Thoughts on OpenStack, Cloud, and Technology.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://delapsley.github.io" # the base hostname & protocol for your site
twitter_username: devlaps
github_username:  delapsley

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal