# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Lapsley (devlaps)
email: devlaps@devlaps.cc
email_name: devlaps
description: > # this means to ignore newlines until "baseurl:"
    Thoughts on OpenStack, Cloud, and Technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.devlaps.cc" # the base hostname & protocol for your site
twitter_username: devlaps
github_username:  devlaps

# Build settings
markdown: kramdown

# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
google_analytics: UA-89548016-1
